src/Entity/DeliveryAdresse.php
<?php

namespace App\Entity;

use App\Repository\DeliveryAdresseRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: DeliveryAdresseRepository::class)]
class DeliveryAdresse
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'deliveryAdresses')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\Column(length: 255)]
    private ?string $City = null;

    #[ORM\Column]
    private ?int $postal_code = null;

    #[ORM\Column(length: 255)]
    private ?string $full_name = null;

    #[ORM\Column]
    private ?int $phone_number = null;

    #[ORM\OneToMany(mappedBy: 'deliveryAdresse', targetEntity: Orders::class)]
    private Collection $orders;

    #[ORM\Column(length: 255)]
    private ?string $adresse = null;

    public function __construct()
    {
        $this->orders = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->City;
    }

    public function setCity(string $City): static
    {
        $this->City = $City;

        return $this;
    }

    public function getPostalCode(): ?int
    {
        return $this->postal_code;
    }

    public function setPostalCode(int $postal_code): static
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getFullName(): ?string
    {
        return $this->full_name;
    }

    public function setFullName(string $full_name): static
    {
        $this->full_name = $full_name;

        return $this;
    }

    public function getPhoneNumber(): ?int
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(int $phone_number): static
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    /**
     * @return Collection<int, Orders>
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function addOrder(Orders $order): static
    {
        if (!$this->orders->contains($order)) {
            $this->orders->add($order);
            $order->setDeliveryAdresse($this);
        }

        return $this;
    }

    public function removeOrder(Orders $order): static
    {
        if ($this->orders->removeElement($order)) {
            // set the owning side to null (unless already changed)
            if ($order->getDeliveryAdresse() === $this) {
                $order->setDeliveryAdresse(null);
            }
        }

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): static
    {
        $this->adresse = $adresse;

        return $this;
    }    
    
    public function __toString()
    {
        return $this->adresse . " " . $this->City . " " . $this->postal_code;
    }
}

src/Entity/Orders.php
<?php

namespace App\Entity;

use App\Repository\OrdersRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OrdersRepository::class)]
class Orders
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'orders')]
    private ?User $user = null;

    #[ORM\Column(length: 11)]
    private ?string $reference = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\OneToMany(mappedBy: 'orders', targetEntity: OrdersDetails::class, orphanRemoval:true, cascade: ['persist', 'remove'])]
    private Collection $ordersDetails;

    #[ORM\ManyToOne(inversedBy: 'orders', cascade: ['persist'])]
    private ?BillingAdresse $billingAdresse = null;

    #[ORM\ManyToOne(inversedBy: 'orders', cascade: ['persist'])]
    private ?DeliveryAdresse $deliveryAdresse = null;

    #[ORM\Column]
    private ?float $total = null;

    public function __construct()
    {
        $this->ordersDetails = new ArrayCollection();
        $this->created_at = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getReference(): ?string
    {
        return $this->reference;
    }

    public function setReference(string $reference): static
    {
        $this->reference = $reference;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection<int, OrdersDetails>
     */
    public function getOrdersDetails(): Collection
    {
        return $this->ordersDetails;
    }

    public function addOrdersDetail(OrdersDetails $ordersDetail): static
    {
        if (!$this->ordersDetails->contains($ordersDetail)) {
            $this->ordersDetails->add($ordersDetail);
            $ordersDetail->setOrdersId($this);
        }

        return $this;
    }

    public function removeOrdersDetail(OrdersDetails $ordersDetail): static
    {
        if ($this->ordersDetails->removeElement($ordersDetail)) {
            // set the owning side to null (unless already changed)
            if ($ordersDetail->getOrdersId() === $this) {
                $ordersDetail->setOrdersId(null);
            }
        }

        return $this;
    }

    public function getBillingAdresse(): ?BillingAdresse
    {
        return $this->billingAdresse;
    }

    public function setBillingAdresse(?BillingAdresse $billingAdresse): static
    {
        $this->billingAdresse = $billingAdresse;

        return $this;
    }

    public function getDeliveryAdresse(): ?deliveryAdresse
    {
        return $this->deliveryAdresse;
    }

    public function setDeliveryAdresse(?deliveryAdresse $deliveryAdresse): static
    {
        $this->deliveryAdresse = $deliveryAdresse;

        return $this;
    }

    public function getTotal(): ?float
    {
        return $this->total;
    }

    public function setTotal(float $total): static
    {
        $this->total = $total;

        return $this;
    }

}

src/Form/OrdersType.php
<?php

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class OrdersType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
        ->add('deliveryAdresse', DeliveryAdresseType::class, [
            'required' => false,
            ])
        ->add('billingAdresse', BillingAdresseType::class, [
            'required' => false,
        ]);
        // Ajoutez d'autres champs nécessaires pour l'entité Orders
        // ->add('submit', SubmitType::class, [
        //     'label' => 'Create Order',
        // ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            // Configure your form options here
        ]);
    }
}

src/Controller/OrdersController.php
<?php

namespace App\Controller;

use Stripe;
use App\Entity\Orders;
use App\Form\OrdersType;
use App\Entity\OrdersDetails;
use App\Entity\BillingAdresse;
use App\Entity\DeliveryAdresse;
use App\Repository\OrdersRepository;
use App\Repository\VoyageRepository;
use Doctrine\ORM\EntityManagerInterface;
use App\Repository\OrdersDetailsRepository;
use App\Repository\BillingAdresseRepository;
use App\Repository\DeliveryAdresseRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/commandes', name: 'orders_')]
class OrdersController extends AbstractController
{
    #[Route('/', name: 'index')]
    public function index(OrdersDetailsRepository $ordersDetailsRepository)
    {
        $user = $this->getUser();
        if ($user == null) {
            $this->addFlash('message', 'Vous devez être connecté pour continuer');
            return $this->redirectToRoute('app_voyage_index');
        }

        $orders = $user->getOrders();

        return $this->render('orders/index.html.twig', [
            'orders' => $orders,
        ]);
    }


    #[Route('/new', name: 'app_order_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager, SessionInterface $session, VoyageRepository $voyageRepository): Response
    {
        // dd($this->getUser());
        $user = $this->getUser();
        if ($user == null) {
            $this->addFlash('message', 'Vous devez être connecté pour continuer');
            return $this->redirectToRoute('app_voyage_index');
        }

        $panier = $session->get('panier', []);
        // dd($panier);
        if ($panier === []) {
            $this->addFlash('message', 'Votre panier est vide');
            return $this->redirectToRoute('app_voyage_index');
        }

        $billingAdresses = $user->getBillingAdresses();
        $deliveryAdresses = $user->getDeliveryAdresses();
        // dd($billingAdresses);

        $order = new Orders();
        $form = $this->createForm(OrdersType::class, $order);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // boucle sur $panier
            $total = 0;
            foreach ($panier as $item => $quantity) {
                $orderDetails = new OrdersDetails();

                // récup le voyage (find = récup par l'id)
                $voyage = $voyageRepository->find($item);

                $price = $voyage->getPrice();

                // add chaque details
                $orderDetails->setVoyagesId($voyage);
                $orderDetails->setPrice($price);
                $orderDetails->setQuantity($quantity);

                // add de la ref
                $order->addOrdersDetail($orderDetails);

                $total += $price * $quantity;
            }
            // dd($total);

            // dd($request->request->get('stripeToken'));
            Stripe\Stripe::setApiKey($_ENV["STRIPE_SECRET"]);
            Stripe\Charge::create([
                "amount" => $total * 100,
                "currency" => "eur",
                "source" => $request->request->get('stripeToken'),
                "description" => "Binaryboxtuts Payment Test"
            ]);

            $deliveryOption = $request->request->get('delivery_option');
            $billingOption = $request->request->get('billing_option');

            // Traitement de l'adresse de livraison
            if ($deliveryOption === 'existing') {
                $deliveryAddressId = $request->request->get('delivery_select');
                $deliveryAddress = $entityManager->getRepository(DeliveryAdresse::class)->find($deliveryAddressId);
                $order->setDeliveryAdresse($deliveryAddress);
            } else {
                $deliveryAddress = new DeliveryAdresse();
                $deliveryAddress->setUser($user);

                // dd($order->getDeliveryAdresse());
                $orderDelivery = $order->getDeliveryAdresse();
                $deliveryAddress->setCity($orderDelivery->getCity());
                $deliveryAddress->setPostalCode($orderDelivery->getPostalCode());
                $deliveryAddress->setFullName($orderDelivery->getFullName());
                $deliveryAddress->setPhoneNumber($orderDelivery->getPhoneNumber());
                $deliveryAddress->setAdresse($orderDelivery->getAdresse());
                $order->setDeliveryAdresse($deliveryAddress);

                $order->getDeliveryAdresse()->setUser($user);
            }

            // Traitement de l'adresse de facturation (similaire à la livraison)
            if ($billingOption === 'existing') {
                $billingAddressId = $request->request->get('billing_select');
                $billingAddress = $entityManager->getRepository(BillingAdresse::class)->find($billingAddressId);
                $order->setBillingAdresse($billingAddress);
            } else {
                $billingAddress = new BillingAdresse();
                $billingAddress->setUser($user);

                $orderBilling = $order->getDeliveryAdresse();
                $billingAddress->setCity($orderBilling->getCity());
                $billingAddress->setPostalCode($orderBilling->getPostalCode());
                $billingAddress->setFullName($orderBilling->getFullName());
                $billingAddress->setPhoneNumber($orderBilling->getPhoneNumber());
                $billingAddress->setAdresse($orderBilling->getAdresse());

                $order->setBillingAdresse($billingAddress);

                $order->getBillingAdresse()->setUser($user);
            }

            // set de user pour getBillingAdresse & getDeliveryAdresse

            // création de la réf
            $firstLetterFirstname = substr($user->getFirstname(), 0, 1);
            $firstLetterLastname = substr($user->getLastname(), 0, 1);
            $currentDate = date('dmy');
            $randomNumber = mt_rand(100, 999);
            $ref = $randomNumber . $firstLetterLastname . $firstLetterFirstname . $currentDate;
            $order->setUser($user);
            $order->setReference($ref);
            $order->setTotal($total);

            // Sauvegardez les entités dans la base de données
            $entityManager->persist($order);
            $entityManager->flush();

            // supp le panier avant de quitter
            $session->remove('panier');

            // Redirigez vers une autre page
            $this->addFlash('success', 'Commande validée!');
            return $this->redirectToRoute('orders_index');
        }

        return $this->render('orders/new.html.twig', [
            'stripe_key' => $_ENV["STRIPE_KEY"],
            'form' => $form->createView(),
            'billings' => $billingAdresses,
            'deliverys' => $deliveryAdresses
            // 'stripe_key' => $_ENV["STRIPE_KEY"],
        ]);
    }
}

templates/orders/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Toutes vos commandes
{% endblock %}

{% block body %}

    <div class="container">
    

        <h3 style="text-align: center;">HISTORIQUE DE VOS COMMANDES :</h3>
        <div class="container-orders">

            <section class="table">
                <div class="table-head">
                    <div>Date</div>
                    <div>N° commande</div>
                    <div>Montant</div>
                    <div class="statut">Statut</div>
                    <div class="head-detail">Détails</div>
                </div>

                <div class="content-orders">
                    {% for order in orders %}
                        <div class="order order{{ order.id }}">
                            <div>{{ order.createdAt|date("d/m/Y") }}</div>
                            <div>N°{{ order.reference }}</div>
                            <div>{{ order.total }} €</div>
                            <div class="statut">
                                {% set dateLimite = "now"|date_modify("-5 days") %}
                                {% if order.createdAt < dateLimite %}
                                    <span>Commande livré</span>
                                {% else %}
                                    <span>En cours de livraison</span>
                                {% endif %}
                            </div>
                            

                            <div class="detail-more detail{{ order.id }}" onclick="toggle({{ order.id }})">
                                <span>Détails</span>
                                <img class="icons" src="{{ asset('images/images_site/svg_icons/chevron-down.svg') }}" alt="afficher les details">
                            </div>
                        </div>
                        <div class="id{{ order.id }} all-details">
                            {% for detailorder in order.getOrdersDetails() %}
                                <div class="detail">
                                    <img src="{{ asset('images/voyages/' ~ detailorder.getVoyagesid().getImages[0].name) }}" alt="image du voyage">
                                    <div class="detail-title">{{ detailorder.getVoyagesid().title }}</div>
                                    <div class="detail-quantity">x{{ detailorder.quantity }} jour(s)</div>
                                    <div class="price">{{ detailorder.quantity * detailorder.price }} €</div>

                                </div>
                            {% endfor %}
                        </div>
                        
                    {% endfor %}
                </div>
            </section>
        </div>
    </div>
		
{% endblock %}

{% block javascripts %}
    <script src="{{ asset('js/orders-index.js') }}"></script>
{% endblock %}

templates/orders/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Passer commande
{% endblock %}

{% block body %}
	<div class="container">

		<div class="form-orders">
			{{ form_start(form, {'action': path('orders_app_order_new'), 'attr': {'id': 'checkout-form'}}) }}
			<h1>PASSER COMMANDE</h1>
			<input type="radio" id="delivery_existing" name="delivery_option" value="existing" checked>
			<label for="delivery_existing">Sélectionner une adresse de livraison</label>
			<select name="delivery_select" id="delivery_select">
				{% for delivery in deliverys %}
					<option value="{{ delivery.id }}">{{ delivery.city }}</option>
				{% endfor %}
			</select>
			<input type="radio" id="delivery_new" name="delivery_option" value="new">
			<label for="delivery_new">Nouvelle adresse de livraison</label>
			{{ form_row(form.deliveryAdresse) }}


			<input type="radio" id="billing_existing" name="billing_option" value="existing" checked>
			<label for="billing_existing">Sélectionner une adresse de facturation</label>
			<select name="billing_select" id="billing_select">
				{% for billing in billings %}
					<option value="{{ billing.id }}">{{ billing.city }}</option>
				{% endfor %}
			</select>
			<input type="radio" id="billing_new" name="billing_option" value="new">
			<label for="billing_new">Nouvelle adresse de facturation</label>
			{{ form_row(form.billingAdresse) }}

			<input type='hidden' name='stripeToken' id='stripe-token-id'>
			<div id="card-element"></div>
			<button class="btn-form" onclick="createToken()">PAYER</button>
            {# {{ form_widget(form.submit, { 'attr': {'class': 'btn-form'}}) }} #}


			{{ form_end(form) }}

		</div>
	</div>
		
{% endblock %}

{% block javascripts %}
	<script src="{{ asset('js/orders-script.js') }}"></script>
	<script src="https://js.stripe.com/v3/" ></script>
	<script>
    	console.log("Stripe Key: " + "{{stripe_key}}");
        var stripe = Stripe("{{stripe_key}}");
        var elements = stripe.elements();
        var cardElement = elements.create('card');
        cardElement.mount('#card-element');
    
        function createToken() {
            document.querySelector(".btn-form").disabled = true;
            stripe.createToken(cardElement).then(function(result) {
				
                     
                if(typeof result.error != 'undefined') {
                    document.querySelector(".btn-form").disabled = false;
                    alert(result.error.message);
                }
     
                // creating token success
                if(typeof result.token != 'undefined') {
                    document.getElementById("stripe-token-id").value = result.token.id;
                    document.getElementById('checkout-form').submit();
                }
            });
        }
    </script>
{% endblock %}